{{- $refs := list $.Values.global.github_ref }}
{{- if eq $.Values.werf.env "test" }}
{{- $refs = concat $refs (list "v2.0.3" "v1.2.294+fix1") }}
{{- end }}

{{- range $_, $ref := $refs }}

{{- $version := splitList "/" $ref | last }}
{{- $versionDNSNormalized := printf "%s" $version | lower | replace "+" "-plus-" | replace "_" "-u-" | replace "." "-dot-" }}

{{- $versionURLNormalized := "" }}
{{- if eq $version "main" }}
{{- $versionURLNormalized = "latest" }}
{{- else }}
{{- $versionURLNormalized = printf "%s" $version | lower | replace "+" "-plus-" | replace "_" "-u-" }}
{{- end }}

{{- $host := pluck $.Values.werf.env $.Values.host | first | default $.Values.host._default  }}
{{- if hasPrefix "review" $.Values.werf.env }}
{{- $host = printf "%s.%s" $.Values.werf.env (pluck "dev" $.Values.host | first | default $.Values.host._default ) | lower }}
{{- end }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Chart.Name }}-{{ $versionDNSNormalized }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Original-URI $request_uri;
      ssi on;
      ssi_silent_errors on;
{{ include "rewrites" $ | indent 6 }}
{{- if eq $.Values.werf.env "production" }}
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
{{- else }}
    nginx.ingress.kubernetes.io/auth-url: http://basic-auth.kube-basic-auth.svc.cluster.local/werfio
{{- end }}
spec:
  tls:
  - hosts:
      - {{ $host }}
      - ru.{{ $host }}
{{- if eq $.Values.werf.env "production" }}
      - www.{{ $host }}
{{- end }}
    secretName: tls-{{ $host }}
  rules:
  - host: {{ $host }}
    http:
      paths:
      - path: /docs/{{ $versionURLNormalized }}/
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $.Chart.Name }}-{{ $versionDNSNormalized }}
            port:
              name: http
      - path: /documentation/{{ $versionURLNormalized }}/
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $.Chart.Name }}-{{ $versionDNSNormalized }}
            port:
              name: http
  - host: ru.{{ $host }}
    http:
      paths:
      - path: /docs/{{ $versionURLNormalized }}/
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $.Chart.Name }}-{{ $versionDNSNormalized }}
            port:
              name: http
      - path: /documentation/{{ $versionURLNormalized }}/
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $.Chart.Name }}-{{ $versionDNSNormalized }}
            port:
              name: http
{{- end }}
